server:
  port: 8184
  servlet:
    context-path: /api

spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://14.103.196.157:3306/liang_mianshi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: kobe200800
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 指定数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      minIdle: 20
      max-active: 200
      max-wait: 2000
      time-between-eviction-runs-millis: 2000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      keepAlive: true
      aop-patterns: "com.springboot.template.dao.*"
      filters: stat,wall,log4j2
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        slf4j:
          enabled: true
          statement-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 1000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: root
        login-password: 123
        allow: 127.0.0.1

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      # password: 123456
      connect-timeout: 1000
# elasticsearch 配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# Knife4j 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.mianshi.backend.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    com.mianshi: DEBUG
    org.springframework.web: DEBUG

jwt:
  secret: liangPiaoSecretKey2024ForJWTTokenGenerationAndValidation
  expiration: 86400000

# 跨域配置
cors:
  allowed-origins: http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
