server:
  port: 8184
  servlet:
    context-path: /api

spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://14.103.196.157:3306/liang_mianshi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: kobe200800
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# Knife4j 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.mianshi.backend.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    com.mianshi: DEBUG
    org.springframework.web: DEBUG

jwt:
  secret: liangPiaoSecretKey2024ForJWTTokenGenerationAndValidation
  expiration: 86400000

# 跨域配置
cors:
  allowed-origins: http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
